# version = "0.0.9"
display:
  # Display control overlays:
  # 3=Artwork only
  # 2=Full overlay displayed
  # 1=Volume icon only.
  # 0=no overlay displayed
  overlay: 2

  # Display Time Bar:
  # 1=time bar displayed
  # 0=no time bar displayed
  timebar: 1

  # mode=0 for pirate audio and display boards with cs pin
  # mode=3 for display boards without cs pin
  mode: 0

  # Turn backlight off when mpd state=stop
  # back on when play restarted
  # blank=0 screen will not blank when mpd state=stop
  # blank=n screen will blank after roughly n seconds when mpd state=stop
  blank: 0

  # Add shadow to text
  # Shadow is displayed below and to the right
  # shadow=0 for no shadow text
  # shadow=n : n is the shadow pixel offset
  shadow: 3

  # switch play/ pause button display
  # [switch of play and pause requested for more intuitive operation;
  #  original coding kept as this is a personal preference]
  # ppbutton = 0 for original play pause putton display
  # ppbutton = 1 for play and pause buttons switched for display
  ppbutton: 0

  # Option for screen to blank on pause
  # pauseblank = 0 for display to stay on
  # pauseblank = 1 for display to blank
  pauseblank: 0

